drop database IF EXISTS user_template;

CREATE TABLE IF NOT EXISTS MAIL_LOGS (
    ID SERIAL PRIMARY KEY ,
    EMAIL TEXT NOT NULL,
    SUBJECT TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);